/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kakao.is.view;

import com.kakao.is.controller.Database;
import com.kakao.is.model.MenuTrolly;
import static com.kakao.is.view.ProdukFrame.MODE_VIEW;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PCSISFO
 */
public class LaporanFrame extends javax.swing.JFrame {

    /**
     * Creates new form LaporanFrame
     */
    static LaporanFrame instance;
    String startDateL, startDateP, endDateL, endDateP;
    String jenisProduk;

    public LaporanFrame() {
        Database.connect_db();
        initComponents();
        radioSemua.setSelected(true);
        //Default laporan

        startDateL = "2018-01-01";
        endDateL = "2021-01-31";
        tampilkan_laporan();
        keranjang = new ArrayList<>();
        startDateP = "2018-01-01";
        endDateP = "2021-01-31";
        jenisProduk = " ";
        tampilkan_produk_terbaik();
    }

    public static LaporanFrame getInstance() {
        if (instance == null) {
            instance = new LaporanFrame();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnTampilkanLaporan = new javax.swing.JButton();
        btnDetailLaporan = new javax.swing.JButton();
        btnCetakLaporan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalPendapatan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboEndTahun = new javax.swing.JComboBox<>();
        comboEndBulan = new javax.swing.JComboBox<>();
        comboStartTgl = new javax.swing.JComboBox<>();
        comboStartTahun = new javax.swing.JComboBox<>();
        comboStartBulan = new javax.swing.JComboBox<>();
        comboEndTgl = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProdukTerbaik = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnTampilkanTerbaik = new javax.swing.JButton();
        btnCetakTerbaik = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        radioSemua = new javax.swing.JRadioButton();
        radioMakanan = new javax.swing.JRadioButton();
        radioMinuman = new javax.swing.JRadioButton();
        comboStartTglP = new javax.swing.JComboBox<>();
        comboStartBulanP = new javax.swing.JComboBox<>();
        comboStartTahunP = new javax.swing.JComboBox<>();
        comboEndTglP = new javax.swing.JComboBox<>();
        comboEndBulanP = new javax.swing.JComboBox<>();
        comboEndTahunP = new javax.swing.JComboBox<>();
        btnDetailTerbaik = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setFocusableWindowState(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(756, 580));

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(756, 580));
        jInternalFrame1.setVisible(true);

        jPanel3.setPreferredSize(new java.awt.Dimension(711, 440));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Awal :");

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "Datetime", "Harga Jual", "Total", "Pembeli", "Kasir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLaporan.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblLaporan);
        if (tblLaporan.getColumnModel().getColumnCount() > 0) {
            tblLaporan.getColumnModel().getColumn(0).setMinWidth(40);
            tblLaporan.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblLaporan.getColumnModel().getColumn(0).setMaxWidth(40);
            tblLaporan.getColumnModel().getColumn(1).setMinWidth(65);
            tblLaporan.getColumnModel().getColumn(1).setPreferredWidth(65);
            tblLaporan.getColumnModel().getColumn(1).setMaxWidth(65);
            tblLaporan.getColumnModel().getColumn(2).setMinWidth(150);
            tblLaporan.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblLaporan.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Akhir :");

        btnTampilkanLaporan.setText("Tampilkan");
        btnTampilkanLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanLaporanActionPerformed(evt);
            }
        });

        btnDetailLaporan.setText("Detail");
        btnDetailLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailLaporanActionPerformed(evt);
            }
        });

        btnCetakLaporan.setText("Cetak");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Total Pendapatan :");

        jLabel5.setText("Rp.");

        txtTotalPendapatan.setText("100000");

        comboEndTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));
        comboEndTahun.setSelectedIndex(3);

        comboEndBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" }));

        comboStartTgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "30", "31" }));

        comboStartTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));

        comboStartBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" }));

        comboEndTgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "30", "31" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(btnCetakLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboStartTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboStartBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboStartTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboEndTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboEndBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboEndTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(447, 447, 447))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(269, 269, 269)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTampilkanLaporan)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetailLaporan)))
                        .addGap(180, 180, 180))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTampilkanLaporan)
                    .addComponent(comboStartTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStartBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStartTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEndTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEndBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEndTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnDetailLaporan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalPendapatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetakLaporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Laporan Transaksi Kakao Mami");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Seluruh Laporan", jPanel1);

        jPanel6.setPreferredSize(new java.awt.Dimension(711, 440));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Awal :");

        tblProdukTerbaik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "Nama Produk", "Terjual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdukTerbaik.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblProdukTerbaik);
        if (tblProdukTerbaik.getColumnModel().getColumnCount() > 0) {
            tblProdukTerbaik.getColumnModel().getColumn(0).setMinWidth(40);
            tblProdukTerbaik.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblProdukTerbaik.getColumnModel().getColumn(0).setMaxWidth(40);
            tblProdukTerbaik.getColumnModel().getColumn(1).setMinWidth(65);
            tblProdukTerbaik.getColumnModel().getColumn(1).setPreferredWidth(65);
            tblProdukTerbaik.getColumnModel().getColumn(1).setMaxWidth(65);
            tblProdukTerbaik.getColumnModel().getColumn(2).setMinWidth(270);
            tblProdukTerbaik.getColumnModel().getColumn(2).setPreferredWidth(270);
            tblProdukTerbaik.getColumnModel().getColumn(2).setMaxWidth(270);
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Akhir :");

        btnTampilkanTerbaik.setText("Tampilkan");
        btnTampilkanTerbaik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanTerbaikActionPerformed(evt);
            }
        });

        btnCetakTerbaik.setText("Cetak");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("List   : ");

        radioSemua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioSemua.setText("Semua");
        radioSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSemuaActionPerformed(evt);
            }
        });

        radioMakanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioMakanan.setText("Makanan");
        radioMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMakananActionPerformed(evt);
            }
        });

        radioMinuman.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioMinuman.setText("Minuman");
        radioMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMinumanActionPerformed(evt);
            }
        });

        comboStartTglP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "30", "31" }));

        comboStartBulanP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" }));

        comboStartTahunP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));

        comboEndTglP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "30", "31" }));

        comboEndBulanP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" }));

        comboEndTahunP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));
        comboEndTahunP.setSelectedIndex(3);

        btnDetailTerbaik.setText("Detail");
        btnDetailTerbaik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailTerbaikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioSemua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioMakanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioMinuman))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStartTglP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStartBulanP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStartTahunP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboEndTglP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboEndBulanP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboEndTahunP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnTampilkanTerbaik)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetailTerbaik)))
                .addGap(93, 93, 93))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(btnCetakTerbaik, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(radioSemua)
                    .addComponent(radioMakanan)
                    .addComponent(radioMinuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTampilkanTerbaik)
                    .addComponent(comboStartTglP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStartBulanP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStartTahunP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEndTglP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEndBulanP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEndTahunP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnCetakTerbaik))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetailTerbaik)
                        .addGap(177, 177, 177))))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("10 Produk Terbaik");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 706, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Produk Terbaik", jPanel2);

        btnClose.setFont(new java.awt.Font("OCR A Extended", 1, 11)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 0, 0));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(716, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane2)
                    .addContainerGap()))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(btnClose)
                .addGap(0, 507, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tampilkan_laporan() {

        //Copy model laporan terlebih dahulu
        DefaultTableModel dtm = (DefaultTableModel) tblLaporan.getModel();
        //Hapus data awalnya
        dtm.getDataVector().removeAllElements();

        String sql;
        sql = "SELECT\n"
                + "	nt.idNota,nt.hargaJual,nt.diskon,nt.total,nt.tunai,nt.tglWaktu,nt.namaPemesan,us.username\n"
                + "FROM\n"
                + "	tb_nota nt\n"
                + "JOIN tb_user us ON us.idUser = nt.idUser\n"
                + "AND DATE(nt.tglWaktu) BETWEEN '" + startDateL + "'AND '" + endDateL + "'\n"
                + "ORDER BY tglWaktu DESC";
        ResultSet hasil = Database.query(sql);
        System.out.println(sql);
        int i = 0, totalPendapatan = 0;
        try {
            //Jika kosong langsung tangkap, dimana hasil.next() == ada
            if (!hasil.next()) {
                String kolom[] = {"", "", "", "", "", "", ""};
                dtm.addRow(kolom);
                txtTotalPendapatan.setText(totalPendapatan + "");
                tblLaporan.setModel(dtm);
                return ;
            } else {
                hasil.previous();
                while (hasil.next()) {
                    //dapatkan data querynya
                    System.out.println("hahah");
                    int idNota = hasil.getInt("idNota");
                    int hargaJual = hasil.getInt("hargaJual");
                    int diskon = hasil.getInt("diskon");
                    int total = hasil.getInt("total");
                    //int tunai = hasil.getInt("tunai");
                    String datetime = hasil.getString("tglWaktu");
                    String pemesan = hasil.getString("namaPemesan");
                    String user = hasil.getString("username");
                    totalPendapatan += total;

                    String kolom[] = {(++i) + "", idNota + "", datetime, "" + hargaJual, "" + total, pemesan, user};
                    dtm.addRow(kolom);

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LaporanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //copykan dtm ke table
        txtTotalPendapatan.setText(totalPendapatan + "");
        tblLaporan.setModel(dtm);
    }

    private void tampilkan_produk_terbaik() {
        DefaultTableModel dtm = (DefaultTableModel) tblProdukTerbaik.getModel();
        dtm.getDataVector().removeAllElements();

        String sql;
        sql = "SELECT\n"
                + "	p.idProduk,p.namaProduk, SUM(banyak) terjual\n"
                + "FROM\n"
                + "	tb_nota n,tb_dt_nota dn,tb_produk p\n"
                + "WHERE\n"
                + "	n.idNota = dn.idNota AND p.idProduk = dn.idProduk AND DATE(n.tglWaktu) BETWEEN '" + startDateP + "'\n"
                + "	AND '" + endDateP + "' " + jenisProduk + " \n"
                + "GROUP BY p.idProduk\n"
                + "ORDER BY terjual DESC LIMIT 10;";
        ResultSet result = Database.query(sql);
        System.out.println(sql);
        int i = 0;
        try {
            
            if (!result.next()) {
                String kolom[] = {"", "", "", "", "", "", ""};
                dtm.addRow(kolom);
                tblProdukTerbaik.setModel(dtm);
                System.out.println("yah");
                return ;
            } else {
                result.previous();
                while (result.next()) {
                    System.out.println("hahah");
                    int idProduk = result.getInt("idProduk");
                    String nama = result.getString("namaProduk");
                    int terjual = result.getInt("terjual");
                    String kolom[] = {(++i) + "", "" + idProduk, nama, "" + terjual};
                    dtm.addRow(kolom);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LaporanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblProdukTerbaik.setModel(dtm);
    }
    private void radioSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSemuaActionPerformed
        // TODO add your handling code here:
        radioMakanan.setSelected(false);
        radioMinuman.setSelected(false);
    }//GEN-LAST:event_radioSemuaActionPerformed

    private void radioMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMakananActionPerformed
        // TODO add your handling code here:
        radioMinuman.setSelected(false);
        radioSemua.setSelected(false);
    }//GEN-LAST:event_radioMakananActionPerformed

    private void radioMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMinumanActionPerformed
        // TODO add your handling code here:
        radioMakanan.setSelected(false);
        radioSemua.setSelected(false);
    }//GEN-LAST:event_radioMinumanActionPerformed

    private void btnTampilkanTerbaikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanTerbaikActionPerformed
        // TODO add your handling code here:
        //untuk jenis
        startDateP = (comboStartTahunP.getSelectedIndex() + 2018) + "-" + (comboStartBulanP.getSelectedIndex() + 1) + "-" + (comboStartTglP.getSelectedIndex() + 1);
        endDateP = (comboEndTahunP.getSelectedIndex() + 2018) + "-" + (comboEndBulanP.getSelectedIndex() + 1) + "-" + (comboEndTglP.getSelectedIndex() + 1);
        if (radioSemua.isSelected()) {
            jenisProduk = " ";
        } else if (radioMakanan.isSelected()) {
            jenisProduk = " AND jenis = 1 ";
        } else {
            jenisProduk = " AND jenis = 2 ";
        }
        tampilkan_produk_terbaik();
    }//GEN-LAST:event_btnTampilkanTerbaikActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        instance = null;
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDetailLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailLaporanActionPerformed
        // TODO add your handling code here:
        int posisi = -1;
        posisi = tblLaporan.getSelectedRow();
        if (posisi != -1) {
            int idNota = Integer.parseInt(tblLaporan.getValueAt(posisi, 1).toString());
            String sql = "CALL receipt(" + idNota + ")";
            System.out.println(sql);
            /*
            Langkah -langkah
            1. Dapatkan seluruh data receipt dari database
            2. pindahkan seluruh data ke array list
            3. dapatkan keterangan2 nya juga
             */
            keranjang.clear();
            ResultSet hasil = Database.query(sql);
            try {
                //dapatkan keterangan static seperti kasir,pembeli,tgl ,diskon,tunai
                hasil.next();
                String datetime = hasil.getDate("tglWaktu").toString();
                String kasir = hasil.getString("username");
                String pembeli = hasil.getString("namaPemesan");
                int diskon = hasil.getInt("diskon");
                int tunai = hasil.getInt("tunai");
                int hargaJual = 0;
                int total = 0;
                int kembali = 0;
                int idProduk;
                String nama;
                int hargaProduk;
                int qty;
                int subTotal;

                do {
                    //pindah ke array list
                    idProduk = hasil.getInt("idProduk");
                    nama = hasil.getString("namaProduk");
                    hargaProduk = hasil.getInt("hargaJual"); //dapat dari produk
                    qty = hasil.getInt("banyak");
                    subTotal = hasil.getInt("subtotal"); //atau manual hargaProduk * qty
                    hargaJual += subTotal;
                    MenuTrolly tmb_barang = new MenuTrolly(idProduk, nama, hargaProduk, qty, subTotal);
                    keranjang.add(tmb_barang);
                } while (hasil.next());

                total = hargaJual - diskon;
                kembali = tunai - total;
                
                
                ReceiptDetailFrame.instance = null;
                ReceiptDetailFrame.MODE = 2;
                ReceiptDetailFrame.set_keterangan(idNota, datetime, kasir, pembeli, hargaJual,
                        diskon, total, tunai, kembali, keranjang);
                ReceiptDetailFrame receipt = ReceiptDetailFrame.getInstance();
               
                receipt.setVisible(true);
                receipt.setLocationRelativeTo(null);
            } catch (SQLException ex) {
                Logger.getLogger(LaporanFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

            JOptionPane.showMessageDialog(this, "Silahkan pilih produk terlebih dahulu",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            this.setVisible(true);
        
        }
    }//GEN-LAST:event_btnDetailLaporanActionPerformed

    private void btnTampilkanLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanLaporanActionPerformed
        // TODO add your handling code here:
        startDateL = (comboStartTahun.getSelectedIndex() + 2018) + "-" + (comboStartBulan.getSelectedIndex() + 1) + "-" + (comboStartTgl.getSelectedIndex() + 1);
        endDateL = (comboEndTahun.getSelectedIndex() + 2018) + "-" + (comboEndBulan.getSelectedIndex() + 1) + "-" + (comboEndTgl.getSelectedIndex() + 1);
        tampilkan_laporan();
    }//GEN-LAST:event_btnTampilkanLaporanActionPerformed

    private void btnDetailTerbaikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailTerbaikActionPerformed
        // TODO add your handling code here:
        ProdukDetailFrame.instance = null;
        int posisi = -1;
        posisi = tblProdukTerbaik.getSelectedRow();
        if (posisi != -1) {
            int baris = tblProdukTerbaik.getSelectedRow();
            ProdukDetailFrame.idProduk = Integer.parseInt(tblProdukTerbaik.getValueAt(baris, 1).toString());
            ProdukDetailFrame.MODE = MODE_VIEW;
 ProdukDetailFrame.DARI = ProdukDetailFrame.DARI_LAPORAN;
               
            ProdukDetailFrame produkdt = ProdukDetailFrame.getInstance();
            produkdt.setVisible(true);
            produkdt.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih produk terlebih dahulu",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnDetailTerbaikActionPerformed
    ArrayList<MenuTrolly> keranjang;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakLaporan;
    private javax.swing.JButton btnCetakTerbaik;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDetailLaporan;
    private javax.swing.JButton btnDetailTerbaik;
    private javax.swing.JButton btnTampilkanLaporan;
    private javax.swing.JButton btnTampilkanTerbaik;
    private javax.swing.JComboBox<String> comboEndBulan;
    private javax.swing.JComboBox<String> comboEndBulanP;
    private javax.swing.JComboBox<String> comboEndTahun;
    private javax.swing.JComboBox<String> comboEndTahunP;
    private javax.swing.JComboBox<String> comboEndTgl;
    private javax.swing.JComboBox<String> comboEndTglP;
    private javax.swing.JComboBox<String> comboStartBulan;
    private javax.swing.JComboBox<String> comboStartBulanP;
    private javax.swing.JComboBox<String> comboStartTahun;
    private javax.swing.JComboBox<String> comboStartTahunP;
    private javax.swing.JComboBox<String> comboStartTgl;
    private javax.swing.JComboBox<String> comboStartTglP;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton radioMakanan;
    private javax.swing.JRadioButton radioMinuman;
    private javax.swing.JRadioButton radioSemua;
    private javax.swing.JTable tblLaporan;
    private javax.swing.JTable tblProdukTerbaik;
    private javax.swing.JLabel txtTotalPendapatan;
    // End of variables declaration//GEN-END:variables
}
