/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kakao.is.view;

import com.kakao.is.controller.Database;
import com.kakao.is.controller.LoginController;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gokil
 */
public class ProdukFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProdukFrame
     */
    public int jenisProduk = 1;
    String SearchByName = "";
    static ProdukFrame instance;
    public static final int MODE_TAMBAH = 1;
    public static final int MODE_EDIT = 2;
    public static final int MODE_VIEW = 3;

    public static final int LIST_MAKANAN = 1;
    public static final int LIST_MINUMAN = 2;
    public static final int LIST_ALL = 3;
    public int current_list;

    public ProdukFrame() {
        initComponents();
        this.current_list = LIST_ALL;
        radioSemua.setSelected(true);
        if(LoginController.getInstance().getCurrentUser().getRole().equals("Manager")){
            //hanya bisa lihat
        }
        tampilkan_produk();
    }

    public static ProdukFrame getInstance() {
        if (instance == null) {
            instance = new ProdukFrame();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        panelListProduk = new javax.swing.JPanel();
        btnTampil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radioSemua = new javax.swing.JRadioButton();
        radioMakanan = new javax.swing.JRadioButton();
        radioMinuman = new javax.swing.JRadioButton();
        txtSearchNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        btnDetailProduk = new javax.swing.JButton();
        btnTambahProduk = new javax.swing.JButton();
        btnEditProduk = new javax.swing.JButton();
        btnHapusProduk = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        setResizable(false);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 3, 17)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List Makanan / Minuman");

        btnTampil.setText("Tampilkan");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        jLabel2.setText("List : ");

        radioSemua.setText("Semua");
        radioSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSemuaActionPerformed(evt);
            }
        });

        radioMakanan.setText("Makanan");
        radioMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMakananActionPerformed(evt);
            }
        });

        radioMinuman.setText("Minuman");
        radioMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMinumanActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Produk :");

        javax.swing.GroupLayout panelListProdukLayout = new javax.swing.GroupLayout(panelListProduk);
        panelListProduk.setLayout(panelListProdukLayout);
        panelListProdukLayout.setHorizontalGroup(
            panelListProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListProdukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSemua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioMakanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioMinuman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchNama, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelListProdukLayout.setVerticalGroup(
            panelListProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListProdukLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(panelListProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampil)
                    .addComponent(jLabel2)
                    .addComponent(radioSemua)
                    .addComponent(radioMakanan)
                    .addComponent(radioMinuman)
                    .addComponent(txtSearchNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
        );

        tblProduk.setAutoCreateRowSorter(true);
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Produk", "Produk", "Stok", "Harga Jual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduk.setShowHorizontalLines(false);
        tblProduk.setShowVerticalLines(false);
        tblProduk.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProduk);

        btnDetailProduk.setText("Detail");
        btnDetailProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailProdukActionPerformed(evt);
            }
        });

        btnTambahProduk.setText("Tambah");
        btnTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProdukActionPerformed(evt);
            }
        });

        btnEditProduk.setText("Ubah");
        btnEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProdukActionPerformed(evt);
            }
        });

        btnHapusProduk.setText("Hapus");
        btnHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusProdukActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("OCR A Extended", 1, 11)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 0, 0));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(panelListProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnTambahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnDetailProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnEditProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnHapusProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelListProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahProduk)
                    .addComponent(btnEditProduk)
                    .addComponent(btnHapusProduk)
                    .addComponent(btnDetailProduk))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void tampilkan_produk() {
        String kolom[] = {"ID Produk", "Produk", "Stok", "Harga Jual"};
        DefaultTableModel tm = new DefaultTableModel(null, kolom);
        String sql = "";
        SearchByName = txtSearchNama.getText();
        String name = "'%"+SearchByName+"%'";
        switch (current_list) {
            case LIST_ALL: {
                sql = "SELECT idProduk,namaProduk,stok,hargaJual FROM tb_produk WHERE namaProduk LIKE "+name;
                break;
            }
            case LIST_MAKANAN: {
                sql = "SELECT idProduk,namaProduk,stok,hargaJual FROM tb_produk "
                        + "WHERE jenis=" + LIST_MAKANAN +" AND namaProduk LIKE "+name;
                break;
            }
            case LIST_MINUMAN: {
                sql = "SELECT idProduk,namaProduk,stok,hargaJual FROM tb_produk "
                        + "WHERE jenis=" + LIST_MINUMAN+" AND namaProduk LIKE "+name;
                break;
            }
        }
        System.out.println(sql);
        ResultSet hasil = Database.query(sql);
        int id, stok, hargaJual;
        String produk;
        try {
            while (hasil.next()) {
                id = hasil.getInt("idProduk");
                produk = hasil.getString("namaProduk");
                stok = hasil.getInt("stok");
                hargaJual = hasil.getInt("hargaJual");

                String detail[] = {id + "", produk, stok + "", hargaJual + ""};
                tm.addRow(detail);
            }
        } catch (Exception ex) {
            Logger.getLogger(ProdukFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
        tblProduk.setModel(tm);
    }
    private void btnHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusProdukActionPerformed
        // TODO add your handling code here:
        int position = -1;
        position = tblProduk.getSelectedRow();
        if (position != -1) {
            int id = Integer.parseInt(tblProduk.getValueAt(position, 0).toString());
            //hapus data
            String sql = "DELETE FROM tb_produk WHERE idProduk = " + id;
            Database.update(sql);
            tampilkan_produk();
            JOptionPane.showMessageDialog(this, "Produk berhasil terhapus", "Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih produk terlebih dahulu",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusProdukActionPerformed

    private void btnTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProdukActionPerformed
        // TODO add your handling code here:

        ProdukDetailFrame.idProduk = 0;
        ProdukDetailFrame.MODE = MODE_TAMBAH;
        //this.setVisible(false);
        ProdukDetailFrame.DARI = ProdukDetailFrame.DARI_PRODUK;
        ProdukDetailFrame produkDetail = ProdukDetailFrame.getInstance();
        produkDetail.setLocationRelativeTo(null);
        //produkDetail.setVisible(true);
    }//GEN-LAST:event_btnTambahProdukActionPerformed

    private void btnEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProdukActionPerformed
        // TODO add your handling code here:
        //refresh terlebih dahulu
        ProdukDetailFrame.instance = null;
        int posisi = -1;
        posisi = tblProduk.getSelectedRow();
        if (posisi != -1) {
            int baris = tblProduk.getSelectedRow();
            ProdukDetailFrame.idProduk = Integer.parseInt(tblProduk.getValueAt(baris, 0).toString());
            ProdukDetailFrame.MODE = MODE_EDIT;
            System.out.println(ProdukDetailFrame.idProduk);
            //this.setVisible(false);
            ProdukDetailFrame.DARI = ProdukDetailFrame.DARI_PRODUK;
            ProdukDetailFrame produkDetail = ProdukDetailFrame.getInstance();
            produkDetail.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih produk terlebih dahulu",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }

        //produkDetail.setVisible(true);
    }//GEN-LAST:event_btnEditProdukActionPerformed

    private void btnDetailProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailProdukActionPerformed
        // TODO add your handling code here:
        ProdukDetailFrame.instance = null;
        int posisi = -1;
        posisi = tblProduk.getSelectedRow();
        if (posisi != -1) {
            int baris = tblProduk.getSelectedRow();
            ProdukDetailFrame.idProduk = Integer.parseInt(tblProduk.getValueAt(baris, 0).toString());
            ProdukDetailFrame.MODE = MODE_VIEW;
            //this.setVisible(false);
            ProdukDetailFrame.DARI = ProdukDetailFrame.DARI_PRODUK;
            ProdukDetailFrame produkdt = ProdukDetailFrame.getInstance();
            produkdt.setVisible(true);
            produkdt.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih produk terlebih dahulu",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnDetailProdukActionPerformed

    private void radioSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSemuaActionPerformed
        // TODO add your handling code here:
        radioMakanan.setSelected(false);
        radioMinuman.setSelected(false);
    }//GEN-LAST:event_radioSemuaActionPerformed

    private void radioMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMakananActionPerformed
        // TODO add your handling code here:
        radioMinuman.setSelected(false);
        radioSemua.setSelected(false);
    }//GEN-LAST:event_radioMakananActionPerformed

    private void radioMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMinumanActionPerformed
        // TODO add your handling code here:
        radioMakanan.setSelected(false);
        radioSemua.setSelected(false);
    }//GEN-LAST:event_radioMinumanActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        if (radioSemua.isSelected()) {
            current_list = LIST_ALL;
        } else if (radioMakanan.isSelected()) {
            current_list = LIST_MAKANAN;
        } else if (radioMinuman.isSelected()) {
            current_list = LIST_MINUMAN;
        } else {
            //if not choose one of them
            JOptionPane.showMessageDialog(this, "Pilih list yang anda inginkan", "Warning",
                    JOptionPane.WARNING_MESSAGE);
        }
        tampilkan_produk();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        instance = null;
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDetailProduk;
    private javax.swing.JButton btnEditProduk;
    private javax.swing.JButton btnHapusProduk;
    private javax.swing.JButton btnTambahProduk;
    private javax.swing.JButton btnTampil;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListProduk;
    private javax.swing.JRadioButton radioMakanan;
    private javax.swing.JRadioButton radioMinuman;
    private javax.swing.JRadioButton radioSemua;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextField txtSearchNama;
    // End of variables declaration//GEN-END:variables
}
