/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kakao.is.view;

import com.kakao.is.controller.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gokil
 */
public class ProdukDetailFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProdukDetailFrame
     */
    public static int idProduk ;
    public static int MODE;
    static ProdukDetailFrame instance = null;
    public ProdukDetailFrame() {
        
        initComponents();
        pilihan(MODE);
        
    }
    public static ProdukDetailFrame getInstance(){
        if(instance == null){
            instance = new ProdukDetailFrame();
        }
        return instance;
    }
    public void pilihan(int mode){
        //ProdukDetailFrame.idProduk = idProduk;
        switch (mode){
            case 1 :{
                //tambah
                
                tambahBaru();
                break;
            }
            case 2 :{
                //edit
                aturUlang(idProduk);
                break;
            }
            case 3 :{
                //view
                tampilkanDetail(idProduk);
                break;
            }
        }
    }
    public void aturUlang(int idProduk){
        tampilkanDetail(idProduk);
        btnEdit.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnBatal.setEnabled(true);
        
        txtNamaProduk.setEnabled(true);
        txtStokProduk.setEnabled(true);
        txtHargaAwal.setEnabled(true);
        txtHargaJual.setEnabled(true);
        radioMakan.setEnabled(true);
        radioMinum.setEnabled(true);
        this.setVisible(true);
        
    }

    public void tampilkanDetail(int idProduk){
        String sql = "SELECT * FROM tb_produk WHERE idProduk = "+idProduk;
        ResultSet hasil = Database.query(sql);
        try {
            hasil.next();
            String nama = hasil.getString("namaProduk");
            int stok = hasil.getInt("stok");
            int hargaAwal = hasil.getInt("hargaAwal");
            int hargaJual = hasil.getInt("hargaJual");
            int idJenis = hasil.getInt("jenis");
            String jenis = (idJenis==1)?"Makanan":"Minuman" ;
            
            if(idJenis==1) radioMakan.setSelected(true) ;else  radioMinum.setSelected(true);
            txtIdProduk.setText(idProduk+"");
            txtNamaProduk.setText(nama);
            txtStokProduk.setText(stok+"");
            txtHargaAwal.setText(hargaAwal+"");
            txtHargaJual.setText(hargaJual+"");
            headerDetail.setText("Detail "+jenis);
            
            // Disable semua
            txtNamaProduk.setEnabled(false);
            txtStokProduk.setEnabled(false);
            txtHargaAwal.setEnabled(false);
            txtHargaJual.setEnabled(false);
            radioMakan.setEnabled(false);
            radioMinum.setEnabled(false);
            
            btnEdit.setEnabled(true);
            btnSimpan.setEnabled(false);
            btnBatal.setEnabled(false);
            
            this.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ProdukDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    public void tambahBaru(){
        
        txtIdProduk.setText("-");
        txtNamaProduk.setText("");
        txtStokProduk.setText("");
        txtHargaAwal.setText("");
        txtHargaJual.setText("");
        headerDetail.setText("Tambah Produk Baru");
        
        //editable
        txtNamaProduk.setEnabled(true);
        txtStokProduk.setEnabled(true);
        txtHargaAwal.setEnabled(true);
        txtHargaJual.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnBatal.setEnabled(true);
        
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        headerDetail = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargaJual = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        radioMakan = new javax.swing.JRadioButton();
        radioMinum = new javax.swing.JRadioButton();
        txtIdProduk = new javax.swing.JLabel();
        txtNamaProduk = new javax.swing.JTextField();
        txtStokProduk = new javax.swing.JTextField();
        txtHargaAwal = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);

        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame1.setVisible(true);

        headerDetail.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        headerDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerDetail.setText("Detail");

        jLabel1.setText("ID Produk");

        jLabel3.setText("Nama");

        stok.setText("Stok");

        jLabel5.setText("Harga Awal");

        hargaJual.setText("Harga Jual");

        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis Produk");

        radioMakan.setText("Makanan");
        radioMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMakanActionPerformed(evt);
            }
        });

        radioMinum.setText("Minuman");
        radioMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMinumActionPerformed(evt);
            }
        });

        txtIdProduk.setText("1010");

        txtNamaProduk.setText("Pecel Jowo");
        txtNamaProduk.setEnabled(false);
        txtNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaProdukActionPerformed(evt);
            }
        });

        txtStokProduk.setText("30");
        txtStokProduk.setToolTipText("");
        txtStokProduk.setEnabled(false);

        txtHargaAwal.setText("10000");
        txtHargaAwal.setEnabled(false);

        txtHargaJual.setText("20000");
        txtHargaJual.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargaJual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioMakan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioMinum))
                    .addComponent(txtIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtHargaJual, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHargaAwal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtStokProduk, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radioMakan)
                    .addComponent(radioMinum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok)
                    .addComponent(txtStokProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaJual)
                    .addComponent(txtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addGap(22, 22, 22))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kakao/is/image/kakao.png"))); // NOI18N
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(headerDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTutup))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean IsValidated(){
        boolean status=true;
        
        return status;
    }
    static int DARI;
    final static int DARI_PRODUK = 1;      
    final static int DARI_LAPORAN = 2;
    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        //this.instance = null;
//        ProdukDetailFrame.getInstance().dispose();
//        System.out.println("hello");
        this.dispose();
        instance = null;
        if(DARI == DARI_PRODUK){
            ProdukFrame.getInstance().setVisible(true);
        ProdukFrame.getInstance().setLocationRelativeTo(null);
        ProdukFrame.getInstance().tampilkan_produk();   
        }else{
            LaporanFrame.getInstance().setVisible(true);
        LaporanFrame.getInstance().setLocationRelativeTo(null);
  
        }
        
         
        
//        instan.setVisible(true);
          //instan.tampilkan_produk();
        //this.dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void txtNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaProdukActionPerformed
        // TODO add your handling code he.re:
    }//GEN-LAST:event_txtNamaProdukActionPerformed

    private void radioMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMinumActionPerformed
        // TODO add your handling code here:
        radioMakan.setSelected(false);
    }//GEN-LAST:event_radioMinumActionPerformed

    private void radioMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMakanActionPerformed
        // TODO add your handling code here:
        radioMinum.setSelected(false);
    }//GEN-LAST:event_radioMakanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        if(MODE==PenjualanFrame.MODE_TAMBAH){
            txtIdProduk.setText("-");
            txtNamaProduk.setText("");
            txtStokProduk.setText("");
            txtHargaAwal.setText("");
            txtHargaJual.setText("");
            radioMakan.setSelected(false);
            radioMinum.setSelected(false);
        }else{
            tampilkanDetail(idProduk);
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:

        if(IsValidated()){

            String nama;
            int stok;
            int hargaAwal = 0;
            int hargaJual ;
            int jenis = 1;
            nama = txtNamaProduk.getText();
            if(!radioMakan.isSelected()) jenis = 2;
            stok = Integer.parseInt(txtStokProduk.getText());
            hargaAwal = Integer.parseInt(txtHargaAwal.getText());
            hargaJual = Integer.parseInt(txtHargaJual.getText());

            //Check data baru atau update
            String sql;
            if(MODE == PenjualanFrame.MODE_EDIT){
                String idProduk = txtIdProduk.getText();
                sql = "UPDATE tb_produk SET namaProduk = \""+nama+"\" ,jenis = "+jenis+
                ", stok = "+stok+", hargaAwal = "+hargaAwal+",hargaJual="+hargaJual+" "
                + "WHERE idProduk="+idProduk;
                JOptionPane.showMessageDialog(this,"Data berhasil dirubah","Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
            }else{
                sql = "INSERT INTO tb_produk(namaProduk,jenis,stok,hargaAwal,hargaJual) "
                + " VALUES (\""+nama+"\","+jenis+","+stok+","+hargaAwal+","+hargaJual+")";
                JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
            }

            System.out.println(sql);
            Database.update(sql);
            if(MODE==PenjualanFrame.MODE_TAMBAH) {
                sql= "SELECT idProduk FROM tb_produk ORDER BY idProduk DESC LIMIT 1";
                ResultSet hasil = Database.query(sql);
                try {
                    hasil.next();
                    idProduk = hasil.getInt("idProduk");
                } catch (SQLException ex) {
                    Logger.getLogger(ProdukDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            tampilkanDetail(idProduk);
            ProdukFrame.getInstance().tampilkan_produk();
           // PenjualanFrame instance = PenjualanFrame.getInstance();
            //instance.tampilkanMenu();
        }else{

        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        MODE = PenjualanFrame.MODE_EDIT;
        aturUlang(ProdukDetailFrame.idProduk);
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnBatal;
    private static javax.swing.JButton btnEdit;
    private static javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel hargaJual;
    private static javax.swing.JLabel headerDetail;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radioMakan;
    private javax.swing.JRadioButton radioMinum;
    private javax.swing.JLabel stok;
    private javax.swing.JTextField txtHargaAwal;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JLabel txtIdProduk;
    private javax.swing.JTextField txtNamaProduk;
    private javax.swing.JTextField txtStokProduk;
    // End of variables declaration//GEN-END:variables
}
