/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kakao.is.view;

import static com.kakao.is.KakaoIS.arrayStaff;
import static com.kakao.is.KakaoIS.listStaff;
import com.kakao.is.controller.Database;
import com.kakao.is.controller.LoginController;
import com.kakao.is.model.Staff;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gokil
 */
public class StaffFrame extends javax.swing.JFrame {

    /**
     * Creates new form StaffFrame
     */
    public StaffFrame() {
        initComponents();
        /*
         Tergantung usernya
         1. Manager hanya bisa melihat daftar staff
         2. Administrator dapat mengedit 
         */
        tampilkan_staff();
        //Privilege
        if(!LoginController.getInstance().getCurrentUser().getRole().equals("Administrator")){
            btnTambah.setVisible(false);
            btnEdit.setVisible(false);
            btnDetail.setVisible(false);
            btnHapus.setVisible(false);
        }
    }
    static StaffFrame instance;

    public static StaffFrame getInstance() {
        if (instance == null) {
            instance = new StaffFrame();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setFocusableWindowState(false);
        setUndecorated(true);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Management Kakao Mami");

        tblStaff.setAutoCreateRowSorter(true);
        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Username", "Nama", "Jabatan", "Jenis Kelamin", "Alamat", "Telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStaff.setShowHorizontalLines(false);
        tblStaff.setShowVerticalLines(false);
        tblStaff.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblStaff);
        if (tblStaff.getColumnModel().getColumnCount() > 0) {
            tblStaff.getColumnModel().getColumn(0).setMinWidth(40);
            tblStaff.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblStaff.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnDetail.setText("Detail");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("OCR A Extended", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnDetail)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        instance = null;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int posisi = -1;
        posisi = tblStaff.getSelectedRow();
        if (posisi != -1) {
            String username = tblStaff.getValueAt(posisi, 1).toString();

            Staff hapusStaff = listStaff.get(username);
            int idStaff = hapusStaff.getIdStaff();
            int idUser = hapusStaff.getIdUser();

            //arrayStaff.remove(hapusStaff); //doesn't work properly
            for (int i = 0; i < arrayStaff.size(); i++) {
                if (arrayStaff.get(i) == hapusStaff) {
                    arrayStaff.remove(i);
                    break;
                }
            }
            listStaff.remove(username);
            //hapus dari database
            //pertama hapus dari tb_dt_user terlebih dahulu

            String sql = "DELETE FROM tb_dt_user WHERE idStaff = " + idStaff;
            Database.update(sql);
            //Hapus dari tb_user
            sql = "DELETE FROM tb_user WHERE idUser = " + idUser;
            Database.update(sql);
            //Hapus dari tb_staff
            sql = "DELETE FROM tb_staff WHERE idStaff = " + idStaff;
            Database.update(sql);

            tampilkan_staff();
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih Staff terlebih dahulu", "Staff", JOptionPane.WARNING_MESSAGE);
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int posisi = -1;
        posisi = tblStaff.getSelectedRow();
        if (posisi != -1) {
            //cari staff nya
            String username = tblStaff.getValueAt(posisi, 1).toString();
            Staff staff = listStaff.get(username);
            //kirim ke detail staff
            StaffDetailFrame.staff = staff;
            StaffDetailFrame.MODE = 3;
            //pindah frame
            StaffDetailFrame detail = StaffDetailFrame.getInstance();
            detail.setVisible(true);
            detail.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih Staff terlebih dahulu", "Staff", JOptionPane.WARNING_MESSAGE);
            this.setVisible(true);
        }
        //produkDetail.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        int posisi = -1;
        posisi = tblStaff.getSelectedRow();
        if (posisi != -1) {
            //cari staff nya
            String username = tblStaff.getValueAt(posisi, 1).toString();
            Staff staff = listStaff.get(username);
            //Jika sama-sama administrator maka tidak dapat membuka (future)
            //kirim ke detail staff
            StaffDetailFrame.staff = staff;
            StaffDetailFrame.MODE = 2;
            //pindah frame
            StaffDetailFrame detail = StaffDetailFrame.getInstance();
            detail.setVisible(true);
            detail.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih Staff terlebih dahulu", "Staff", JOptionPane.WARNING_MESSAGE);

            this.setVisible(true);
        }
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        StaffDetailFrame.MODE = 1;
        //pindah frame
        StaffDetailFrame detail = StaffDetailFrame.getInstance();
        detail.setVisible(true);
        detail.setLocationRelativeTo(null);
        //produkDetail.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed
    public void tampilkan_staff() {
        DefaultTableModel dtm = (DefaultTableModel) tblStaff.getModel();
        dtm.getDataVector().removeAllElements();
        int i = 0;
        for (i = 0; i < arrayStaff.size(); i++) {
            Staff cur = arrayStaff.get(i);

            String username = cur.getUsername();
            String nama = cur.getNamaStaff();
            String jabatan = cur.getJabatan();
            String jk = cur.getJk() == 'L' ? "Laki-Laki" : "Perempuan";
            String alamat = cur.getAlamat();
            String telp = cur.getTelp();
            String kolom[] = {(i + 1) + "", username, nama,jabatan, jk, alamat, telp};
            dtm.addRow(kolom);
        }
        tblStaff.setModel(dtm);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblStaff;
    // End of variables declaration//GEN-END:variables
}
