/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kakao.is.view;

import static com.kakao.is.KakaoIS.arrayStaff;
import static com.kakao.is.KakaoIS.listStaff;
import static com.kakao.is.KakaoIS.listUser;
import com.kakao.is.controller.Database;
import com.kakao.is.model.Staff;
import com.kakao.is.model.User;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gokil
 */
public class StaffDetailFrame extends javax.swing.JFrame {

    /**
     * Creates new form StaffDetailFrame
     */
    final int MODE_TAMBAH = 1;
    final int MODE_TAMPIL = 2;
    final int MODE_EDIT = 3;
    static int MODE = 2;
    static StaffDetailFrame instance;
    static Staff staff;

    public StaffDetailFrame() {
        initComponents();
        pilih_mode();

    }

    void pilih_mode() {
        switch (MODE) {
            case MODE_TAMBAH: {
                staff = null;
                txtIdUser.setText("-");
                txtUsername.setText("");
                txtPassword.setText("");
                comboRole.setEnabled(true);
                txtNama.setText("");
                radioLaki.setEnabled(true);
                radioLaki.setSelected(true); //default
                radioPerempuan.setEnabled(true);
                comboJabatan.setEnabled(true);
                txtTelp.setText("");
                txtAlamat.setText("");
                atur_ulang();
                break;
            }
            case MODE_TAMPIL: {
                tampilkan_staff();
                txtUsername.setEnabled(false);
                txtPassword.setEnabled(false);
                comboRole.setEnabled(false);
                txtNama.setEnabled(false);
                radioLaki.setEnabled(false);
                radioPerempuan.setEnabled(false);
                comboJabatan.setEnabled(false);
                txtTelp.setEnabled(false);
                txtAlamat.setEnabled(false);
                btnEdit.setEnabled(true);
                btnSimpan.setEnabled(false);
                btnBatal.setEnabled(false);
                break;
            }
            case MODE_EDIT: {
                tampilkan_staff();
                atur_ulang();
                break;
            }
        }
    }

    public static StaffDetailFrame getInstance() {
        if (instance == null) {
            instance = new StaffDetailFrame();
        }
        return instance;
    }

    void tampilkan_staff() {
        txtIdUser.setText(staff.getIdUser() + "");
        txtUsername.setText(staff.getUsername());
        txtPassword.setText(staff.getPassword());
        System.out.println(staff.getRole() + "--=");
        switch (staff.getRole()) {
            case "Staff":
                comboRole.setSelectedIndex(0);
                break;
            case "Manager":
                comboRole.setSelectedIndex(1);
                break;
            case "Administrator":
                comboRole.setSelectedIndex(2);
                break;
        }
        System.out.println(staff.getJabatan() + "--=");
        txtNama.setText(staff.getNamaStaff());
        if (staff.getJk() == 'L') {
            radioLaki.setSelected(true);
            radioPerempuan.setSelected(false);
        } else {
            radioPerempuan.setSelected(true);
            radioLaki.setSelected(false);
        }

        switch (staff.getJabatan()) {
            case "Staff":
                comboJabatan.setSelectedIndex(0);
                break;
            case "Manager":
                comboJabatan.setSelectedIndex(1);
                break;
            case "Owner":
                comboJabatan.setSelectedIndex(2);
                break;
        }

        txtTelp.setText(staff.getTelp());
        txtAlamat.setText(staff.getAlamat());
    }

    void atur_ulang() {
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        comboRole.setEnabled(true);
        txtNama.setEnabled(true);
        radioLaki.setEnabled(true);
        radioPerempuan.setEnabled(true);
        comboJabatan.setEnabled(true);
        txtTelp.setEnabled(true);
        txtAlamat.setEnabled(true);
        btnEdit.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnBatal.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchzecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        headerDetail = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargaJual = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        radioLaki = new javax.swing.JRadioButton();
        radioPerempuan = new javax.swing.JRadioButton();
        txtIdUser = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        comboJabatan = new javax.swing.JComboBox<>();
        comboRole = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);

        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame1.setFocusTraversalPolicyProvider(true);
        jInternalFrame1.setVisible(true);

        headerDetail.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        headerDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerDetail.setText("Detail User");

        jLabel1.setText("ID Staff");

        jLabel3.setText("Nama");

        stok.setText("Jabatan");

        jLabel5.setText("Role");

        hargaJual.setText("Telp");

        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis Kelamin");

        radioLaki.setText("Laki-laki");
        radioLaki.setEnabled(false);
        radioLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLakiActionPerformed(evt);
            }
        });

        radioPerempuan.setText("Perempuan");
        radioPerempuan.setEnabled(false);
        radioPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPerempuanActionPerformed(evt);
            }
        });

        txtIdUser.setText("1010");

        txtNama.setText("Pecel Jowo");
        txtNama.setEnabled(false);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel6.setText("Username");

        txtUsername.setText("Pecel Jowo");
        txtUsername.setEnabled(false);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jLabel7.setText("Password");

        txtPassword.setText("jPasswordField1");
        txtPassword.setEnabled(false);

        comboJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Manager", "Owner" }));
        comboJabatan.setEnabled(false);
        comboJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJabatanActionPerformed(evt);
            }
        });

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Manager", "Administrator" }));
        comboRole.setEnabled(false);
        comboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoleActionPerformed(evt);
            }
        });

        jLabel8.setText("Alamat");

        txtTelp.setText("Pecel Jowo");
        txtTelp.setEnabled(false);
        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });

        txtAlamat.setEnabled(false);
        jScrollPane1.setViewportView(txtAlamat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(radioLaki)
                        .addGap(18, 18, 18)
                        .addComponent(radioPerempuan)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(stok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addComponent(comboJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(radioLaki)
                            .addComponent(radioPerempuan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stok)
                            .addComponent(comboJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hargaJual)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addGap(22, 22, 22))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kakao/is/image/kakao.png"))); // NOI18N
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(headerDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTutup))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        MODE = 3;
        pilih_mode();
    }//GEN-LAST:event_btnEditActionPerformed
    int getId() {
        //untuk saat ini id user dan id staff sama
        int id = -1;
        String sql = "SELECT idUser FROM tb_user ORDER BY idUser DESC LIMIT 1";
        ResultSet hasil = Database.query(sql);
        try {
            hasil.next();
            id = hasil.getInt("idUser");
        } catch (SQLException ex) {
            Logger.getLogger(StaffDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        //tambahkan ke dictionary,array,dan database
        if (isValidated()) {
            String username = txtUsername.getText();
            String password = txtPassword.getText();
            String namaStaff = txtNama.getText();
            char jk = radioLaki.isSelected() ? 'L' : 'P';
            int idRole = 3; //default staff
            String role = "";
            switch (comboRole.getSelectedIndex()) {
                case 0: {
                    idRole = 3;
                    role = "Staff";
                    break;
                }
                case 1: {
                    idRole = 2;
                    role = "Manager";
                    break;
                }
                case 2: {
                    idRole = 1;
                    role = "Administrator";
                    break;
                }
            }

            int idJabatan = 2;
            String jabatan = "";
            switch (comboJabatan.getSelectedIndex()) {
                case 0: {
                    idJabatan = 2;
                    jabatan = "Staff";
                    break;
                }
                case 1: {
                    idJabatan = 1;
                    jabatan = "Manager";
                    break;
                }
                case 2: {
                    idJabatan = 3;
                    jabatan = "Owner";
                    break;
                }
            }
            String telp = txtTelp.getText();
            String alamat = txtAlamat.getText();
            if (MODE == MODE_TAMBAH) {
                int id = getId();
                id = (id == -1) ? 1 : id + 1;

                User userbaru = new User(id, username, password, idRole, role);
                Staff staffbaru = new Staff(id, username, password, idRole, role, id, namaStaff, jk, alamat, telp, jabatan);
                listUser.put(username, userbaru);
                listStaff.put(username, staffbaru);
                arrayStaff.add(staffbaru);
                staff = staffbaru;// ganti currentnya
                //insert ke user terlebih dahulu
                String sql = "INSERT INTO tb_user VALUES (" + id + ",\"" + username + "\",\"" + password + "\")";
                Database.update(sql);
                System.out.println(sql);
                //insert ke staff
                sql = "INSERT INTO tb_staff VALUES (" + id + ",\"" + namaStaff + "\",'" + jk + "',\"" + alamat + "\",\"" + telp + "\"," + idJabatan + ")";
                Database.update(sql);
                System.out.println(sql);
                //insert ke detail user
                sql = "INSERT INTO tb_dt_user VALUES (" + id + "," + id + "," + idRole + ")";
                Database.update(sql);
                MODE = 2;
                pilih_mode();
                System.out.println(sql);
            } else {
                //Update class
                //sebelum diganti
                User upUser = listUser.get(staff.getUsername());
                upUser.setIdRole(idRole);
                upUser.setRole(role);
                upUser.setPassword(password);

                staff.setNamaStaff(namaStaff);
                staff.setTelp(telp);
                staff.setJk(jk);
                staff.setJabatan(jabatan);
                staff.setAlamat(alamat);
                staff.setIdRole(idRole);
                staff.setRole(role);
                staff.setPassword(password);
                if (!username.equals(upUser.getUsername())) {
                    //replace listUser dan listStaff
                    listUser.remove(upUser.getUsername());
                    upUser.setUsername(username);
                    listUser.put(username, upUser);

                    listStaff.remove(upUser.getUsername());
                    staff.setUsername(username);
                    listStaff.put(username, staff);

                }

                //update database
                //update tb_user
                String sql = "UPDATE tb_user \n"
                        + "SET username = \"" + username + "\" , `password`=\"" + password + "\"\n"
                        + "WHERE idUser = " + staff.getIdUser();
                Database.update(sql);
                System.out.println(sql);

                //update tb_staff
                sql = "UPDATE `tb_staff` \n"
                        + "SET `namaStaff` = '" + namaStaff + "', `jk` = '" + jk + "', `alamat` = '" + alamat + "', `telp` = '" + telp + "', `idJabatan` = '" + idJabatan + "' \n"
                        + "WHERE `idStaff` = " + staff.getIdStaff() + ";";
                Database.update(sql);
                System.out.println(sql);

                //update tb_detail
                sql = "UPDATE tb_dt_user"
                        + " SET idRole ='" + idRole + "' "
                        + "WHERE idUser = '" + staff.getIdUser() + "'";
                Database.update(sql);
                System.out.println(sql);
                StaffFrame.getInstance().tampilkan_staff();
                MODE = 2;
                pilih_mode();
            }
            JOptionPane.showMessageDialog(this, "Data Staff telah tersimpan", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    boolean isValidated() {
        boolean validated = true;
        //Check pass
        if (txtPassword.getText().isEmpty()) {
            validated = false;
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong", "Warning Password", JOptionPane.WARNING_MESSAGE);
            return validated;
        }
        /*
            Check username
         */
        //Cek username apakah sudah dipakai
        String sql = "SELECT username FROM tb_user WHERE username='" + txtUsername.getText() + "'";
        System.out.println(sql);
        ResultSet hasil = Database.query(sql);
        try {
            

            if (MODE == MODE_TAMBAH) {
                //Ketika hasil.next() dipanggil maka akan mengembalikan nilai boolean
                // jika ada item / tidak empty maka hasilnya true, dan false sebaliknya
                if (hasil.next()) {
                    validated = false;
                    JOptionPane.showMessageDialog(this, "Username telah terpakai", "Warning Username", JOptionPane.WARNING_MESSAGE);
                    return validated;
                }

                return validated;
            } else {
                //Mode edit
                if (txtUsername.getText().equals(staff.getUsername())) {
                    //tidak masalah
                    return true;
                } else {
                    //jika diganti tapi hasil ganti ternyata sudah ada yang punya
                    if (hasil.next()) {
                        validated = false;
                        JOptionPane.showMessageDialog(this, "Username telah terpakai", "Warning Username", JOptionPane.WARNING_MESSAGE);
                        return validated;
                    }

                }
                
                /*------------------------------------ */
            }

        } catch (SQLException ex) {
            Logger.getLogger(StaffDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        //pilih tampilan sebelumnya
        if (staff == null) {
            //ulangi lagi
            pilih_mode();
            comboJabatan.setSelectedIndex(0);
            comboRole.setSelectedIndex(0);
        } else {
            //jika edit maka kembalikan ke semula, atau mode tampil
            MODE = 3;
            pilih_mode();
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void radioLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLakiActionPerformed
        // TODO add your handling code here:
        radioPerempuan.setSelected(false);
    }//GEN-LAST:event_radioLakiActionPerformed

    private void radioPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPerempuanActionPerformed
        // TODO add your handling code here:
        radioLaki.setSelected(false);
    }//GEN-LAST:event_radioPerempuanActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code he.re:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        this.dispose();
        
        instance = null;
        StaffFrame.getInstance().setVisible(true);
        StaffFrame.getInstance().tampilkan_staff();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void comboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRoleActionPerformed

    private void comboJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJabatanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnBatal;
    private static javax.swing.JButton btnEdit;
    private static javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> comboJabatan;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JLabel hargaJual;
    private static javax.swing.JLabel headerDetail;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioLaki;
    private javax.swing.JRadioButton radioPerempuan;
    private javax.swing.JLabel stok;
    private javax.swing.JTextPane txtAlamat;
    private javax.swing.JLabel txtIdUser;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
